# Documentation at https://goreleaser.com
project_name: tparse

gomod:
  proxy: true

builds:
  - env:
      - CGO_ENABLED=0
    # main: .
    binary: tparse
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    # Custom ldflags templates.
    # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser`.
    ldflags:
      - -s -w

# You can disable this pipe in order to not upload any artifacts.
# Defaults to false.
release:
  disable: false

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  use: github
  sort: asc
  # Commit messages matching the regexp listed here will be removed from
  # the changelog.
  filters:
    exclude:
      - "^docs:"
      - "^test:"
