sudo: false

language: go

before_install:
  - go get -u github.com/mfridman/tparse

go:
  - "1.11"
  - "1.12"

branches:
  only:
    - master
    - devel

script:
  - tparse --version
  - go test -race -v ./parse -json -cover | tparse -all -smallscreen